# code: language=ansible

all:
  children:
    flower_server:
      hosts:
        host_1:
          ansible_host: 192.168.1.105
          ansible_user: suav
          ansible_become_password: abc123
    flower_clients:
      hosts: {}
  vars:
    ansible_connection: ssh
