---
- name: Test
  hosts: remotemachines
  vars:
    ansible_timeout: 20
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print the message
      ansible.builtin.debug:
        msg: flower message
        